namespace VNet.ProceduralGeneration.Cosmological.Configuration
{
    internal static class ConfigConstants
    {
        internal static int MaxDegreesOfParallelismLevel1 { get; } = Environment.ProcessorCount;
        internal static int MaxDegreesOfParallelismLevel2 { get; } = Environment.ProcessorCount - 2 > 1 ? Environment.ProcessorCount - 2 : 1;
        internal static int MaxDegreesOfParallelismLevel3 { get; } = Environment.ProcessorCount - 4 > 1 ? Environment.ProcessorCount - 4 : 1;
        internal static int MaxDegreesOfParallelismLevel4 { get; } = Environment.ProcessorCount - 6 > 1 ? Environment.ProcessorCount - 6 : 1;
        internal static float DimensionX { get; } = 100f;
        internal static float DimensionY { get; } = 100f;
        internal static float DimensionZ { get; } = 100f;
        internal static double MinDarkEnergyPercent { get; } = 65.0;
        internal static double MaxDarkEnergyPercent { get; } = 75.0;
        internal static double MinDarkMatterPercent { get; } = 20.0;
        internal static double MaxDarkMatterPercent { get; } = 30.0;
        internal static double MinBaryonicMatterPercent { get; } = 4.0;
        internal static double MaxBaryonicMatterPercent { get; } = 6.0;
        internal static float MinUniverseAge { get; } = 5e9f;                                    // years
        internal static float MaxUniverseAge { get; } = 20e9f;                                   // years
        internal static double BaselineExpansionRate { get; } = 67.5;                            // km/s/Mpc
        internal static double BaselineCosmicMicrowaveBackground { get; } = 2.735;               // Kelvin
        internal static float MinConnectivityFactor { get; } = 5e9f;
        internal static float MaxConnectivityFactor { get; } = 20e9f;
        internal static int BaryonicMatterNodeBaseCount { get; } = 300;
        internal static double BaryonicMatterNodeCountAgeFactor { get; } = 5.0;
        internal static double BaryonicMatterNodeCountMassFactor { get; } = 1 / 1e30;
        internal static double BaryonicMatterNodeCountSizeFactor { get; } = 1 / 1e9;
        internal static double BaryonicMatterNodeCountBaryonicMatterPercentFactor { get; } = 100;
        internal static double BaryonicMatterNodeCountDarkMatterPercentFactor { get; } = 200;
        internal static double BaryonicMatterNodeCountDarkEnergyPercentFactor { get; } = 100;
        internal static int BaryonicMatterFilamentBaseCount { get; } = 1000;
        internal static double BaryonicMatterFilamentCountAgeFactor { get; } = 10.0;
        internal static double BaryonicMatterFilamentCountMassFactor { get; } = 1 / 1e30;
        internal static double BaryonicMatterFilamentCountSizeFactor { get; } = 1 / 1e9;
        internal static double BaryonicMatterFilamentCountBaryonicMatterPercentFactor { get; } = 100;
        internal static double BaryonicMatterFilamentCountDarkMatterPercentFactor { get; } = 150;
        internal static double BaryonicMatterFilamentCountDarkEnergyPercentFactor { get; } = 100;
        internal static int BaryonicMatterSheetBaseCount { get; } = 300;
        internal static double BaryonicMatterSheetCountAgeFactor { get; } = 5.0;
        internal static double BaryonicMatterSheetCountMassFactor { get; } = 1 / 1e30;
        internal static double BaryonicMatterSheetCountSizeFactor { get; } = 1 / 1e9;
        internal static double BaryonicMatterSheetCountBaryonicMatterPercentFactor { get; } = 100;
        internal static double BaryonicMatterSheetCountDarkMatterPercentFactor { get; } = 150;
        internal static double BaryonicMatterSheetCountDarkEnergyPercentFactor { get; } = 100;
        internal static int BaryonicMatterVoidBaseCount { get; } = 1500;
        internal static double BaryonicMatterVoidCountAgeFactor { get; } = 8.0;
        internal static double BaryonicMatterVoidCountMassFactor { get; } = 1 / 1e30;
        internal static double BaryonicMatterVoidCountSizeFactor { get; } = 1 / 1e9;
        internal static double BaryonicMatterVoidCountBaryonicMatterPercentFactor { get; } = 100;
        internal static double BaryonicMatterVoidCountDarkEnergyPercentFactor { get; } = 100;
        internal static int DarkMatterNodeBaseCount { get; } = 500;
        internal static double DarkMatterNodeCountAgeFactor { get; } = 6.0;
        internal static double DarkMatterNodeCountMassFactor { get; } = 1 / 1e30;
        internal static double DarkMatterNodeCountSizeFactor { get; } = 1 / 1e9;
        internal static double DarkMatterNodeCountBaryonicMatterPercentFactor { get; } = 200;
        internal static double DarkMatterNodeCountDarkMatterPercentFactor { get; } = 100;
        internal static double DarkMatterNodeCountDarkEnergyPercentFactor { get; } = 100;
        internal static int DarkMatterFilamentBaseCount { get; } = 1500;
        internal static double DarkMatterFilamentCountAgeFactor { get; } = 12.0;
        internal static double DarkMatterFilamentCountMassFactor { get; } = 1 / 1e30;
        internal static double DarkMatterFilamentCountSizeFactor { get; } = 1 / 1e9;
        internal static double DarkMatterFilamentCountBaryonicMatterPercentFactor { get; } = 200;
        internal static double DarkMatterFilamentCountDarkMatterPercentFactor { get; } = 100;
        internal static double DarkMatterFilamentCountDarkEnergyPercentFactor { get; } = 100;
        internal static int DarkMatterSheetBaseCount { get; } = 500;
        internal static double DarkMatterSheetCountAgeFactor { get; } = 7.0;
        internal static double DarkMatterSheetCountMassFactor { get; } = 1 / 1e30;
        internal static double DarkMatterSheetCountSizeFactor { get; } = 1 / 1e9;
        internal static double DarkMatterSheetCountBaryonicMatterPercentFactor { get; } = 200;
        internal static double DarkMatterSheetCountDarkMatterPercentFactor { get; } = 100;
        internal static double DarkMatterSheetCountDarkEnergyPercentFactor { get; } = 100;
        internal static int DarkMatterVoidBaseCount { get; } = 1400;
        internal static double DarkMatterVoidCountAgeFactor { get; } = 7.0;
        internal static double DarkMatterVoidCountMassFactor { get; } = 1 / 1e30;
        internal static double DarkMatterVoidCountSizeFactor { get; } = 1 / 1e9;
        internal static double DarkMatterVoidCountDarkMatterPercentFactor { get; } = 100;
        internal static double DarkMatterVoidCountDarkEnergyPercentFactor { get; } = 150;
        internal static float TopologyBaryonicMatterNodeDensityThresholdFactor { get; } = 1.2f;
        internal static float TopologyBaryonicMatterNodeGradientMagnitudeThresholdFactor { get; } = 0.2f;
        internal static float TopologyBaryonicMatterNodeIntensityThresholdFactor { get; } = 1.2f;
        internal static float TopologyBaryonicMatterNodeMergeDistanceThresholdFactor { get; } = 0.2f;
        internal static float TopologyBaryonicMatterNodeMinDistanceThresholdFactor { get; } = 1.2f;
        internal static float TopologyBaryonicMatterNodeMaxPositionalOffset { get; } = 0.2f;
        internal static float TopologyDarkMatterNodeDensityThresholdFactor { get; } = 1.2f;
        internal static float TopologyDarkMatterNodeGradientMagnitudeThresholdFactor { get; } = 0.2f;
        internal static float TopologyDarkMatterNodeIntensityThresholdFactor { get; } = 1.2f;
        internal static float TopologyDarkMatterNodeMergeDistanceThresholdFactor { get; } = 0.2f;
        internal static float TopologyDarkMatterNodeMinDistanceThresholdFactor { get; } = 1.2f;
        internal static float TopologyDarkMatterNodeMaxPositionalOffset { get; } = 0.2f;
    }
}